version: '3.8'

services:
  database:
    image: postgres:16-alpine
    env_file:
      - './.env'
    volumes:
      - mollysfs_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  mollysfs_db:
